import {
  // arrows
  IconArrowUp, IconArrowDown, IconArrowLeft, IconArrowRight,
  IconChevronUp, IconChevronDown,
  IconArrowUpRight, IconArrowDownLeft, IconArrowDownRight,
  IconArrowsMove, IconArrowsMinimize,
  IconArrowsSort, IconSortAscending, IconSortDescending,
  // ui basics
  IconEye, IconEyeOff, IconLayoutSidebarLeftCollapse, IconLayoutSidebarLeftExpand,
  IconExternalLink, IconPlus, IconMinus, IconX, IconCheck,
  IconDots, IconGripVertical, IconGripHorizontal, IconDialpad,
  IconList, IconMenu2, IconTable, IconFilter, IconFilterX,
  IconLayoutKanban,
  // files / media
  IconFile, IconFileDescription, IconFilePlus, IconPhoto, IconCalendar,
  IconClipboardCheck, IconTimelineEvent, IconBox,
  // communication
  IconMail, IconMessage, IconMessageCircle, IconBell, IconBellRinging,
  IconPaperclip, IconShare, IconShare2, IconPhone, IconUsers,
   IconSearch, IconWorld, IconRefresh, IconUpload, IconTag,
  // content / social
  IconStar, IconHeart, IconHeartFilled,
  IconLock, IconLockOpen, IconTrash, IconEdit, IconEditCircle,
  // business / crm / finance
  IconBuildingSkyscraper, IconBuildingCommunity, IconBriefcase,
  IconSchool, IconStethoscope, IconChartBar, IconCash, IconCurrencyDollar,
  IconShoppingCart, IconTractor, IconScale,
  IconReportMoney, IconCoins, IconHierarchy, IconTools, IconSettings,
  // misc
  IconFolder, IconFolderOpen, IconCrop, IconScan, IconLink, IconMap,
  IconId, IconHelp, IconCircle, IconCircleDot
} from "@tabler/icons-react";

export const iconMap = {
  // arrows
  "up-line": IconArrowUp,
  "small-up": IconChevronUp,
  "down": IconArrowDown,
  "small-down": IconChevronDown,
  "right": IconArrowRight,
  "left": IconArrowLeft,
  "up-arrow": IconArrowUp,
  "down-arrow": IconArrowDown,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  "arrow-up-right": IconArrowUpRight,
  "arrow-down-left": IconArrowDownLeft,
  "arrow-down-right": IconArrowDownRight,
  "move": IconArrowsMove,
//   "expand": IconArrowsExpand,
  "collapse": IconArrowsMinimize,
//   "expand-alt": IconArrowsExpand,
  "shrink": IconArrowsMinimize,
  "sort": IconArrowsSort,
  "sort-ascending": IconSortAscending,
  "sort-descending": IconSortDescending,
  "both": IconArrowsSort,
  "select": IconArrowsSort,

  // ui basics
  "unhide": IconEye,
  "hide": IconEyeOff,
  "sidebar-collapse": IconLayoutSidebarLeftCollapse,
  "sidebar-expand": IconLayoutSidebarLeftExpand,
  "change": IconArrowsSort,
  "external-link": IconExternalLink,
  "small-add": IconPlus,
  "add": IconPlus,
  "remove": IconMinus,
  "close": IconX,
  "close-alt": IconX,
  "check": IconCheck,
  "tick": IconCheck,
  "dot-horizontal": IconDots,
  "dot-vertical": IconDots,
  "drag": IconGripVertical,
  "drag-sm": IconGripHorizontal,
  "dialpad": IconDialpad,
  "insert-below": IconFilePlus,
  "insert-above": IconFilePlus,
  "group-by": IconHierarchy,
  "kanban": IconLayoutKanban,
//   "gantt": IconChartGantt,
  "filter": IconFilter,
  "filter-x": IconFilterX,
  "list": IconList,
  "menu": IconMenu2,
  "table": IconTable,
  "table_2": IconTable,

  // communication
  "notification": IconBell,
  "notification-with-indicator": IconBellRinging,
  "message": IconMessage,
  "message-1": IconMessage,
  "small-message": IconMessageCircle,
  "comment": IconMessageCircle,
  "unread-status": IconBellRinging,
  "read-status": IconBell,
  "mark-as-read": IconClipboardCheck,
  "mail": IconMail,
  "calendar": IconCalendar,
  "assign": IconClipboardCheck,
  "customer": IconUsers,
  "share": IconShare,
  "share-people": IconShare2,
  "call": IconPhone,
  "users": IconUsers,
  "support": IconHelp,

  // content / media
  "refresh": IconRefresh,
  "upload": IconUpload,
  "tag": IconTag,
  "restriction": IconLock,
  "attachment": IconPaperclip,
  "view": IconEye,
  "full-page": IconLayoutSidebarLeftExpand,
  "crop": IconCrop,
  "scan": IconScan,
  "link-url": IconLink,
  "map": IconMap,
  "search": IconSearch,
  "website": IconWorld,
  "file": IconFile,
  "list-alt": IconFileDescription,
  "milestone": IconTimelineEvent,
  "small-file": IconFile,
  "image": IconPhoto,
  "image-view": IconPhoto,
  "today": IconCalendar,
  "primitive-dot": IconCircleDot,

  // status
  "heart": IconHeart,
  "heart-active": IconHeartFilled,
  "lock": IconLock,
  "unlock": IconLockOpen,
  "delete": IconTrash,
  "delete-active": IconTrash,
  "pen": IconEdit,
  "edit": IconEdit,
  "edit-fill": IconEditCircle,
  "review": IconEdit,
  "star": IconStar,

  // business / crm / finance
  "organization": IconBuildingSkyscraper,
  "non-profit": IconBuildingCommunity,
  "projects": IconBriefcase,
  "project": IconBriefcase,
  "project-1": IconBriefcase,
  "project-2": IconBriefcase,
  "folder-open": IconFolderOpen,
  "folder-normal": IconFolder,
  "loan": IconCurrencyDollar,
  "money-coins-1": IconCoins,
  "integration": IconHierarchy,
  "hr": IconId,
  "getting-started": IconHelp,
  "education": IconSchool,
  "customization": IconTools,
  "crm": IconBriefcase,
  "equity": IconScale,
  "buying": IconShoppingCart,
  "sell": IconShoppingCart,
  "retail": IconShoppingCart,
  "assets": IconBox,
  "agriculture": IconTractor,
  "accounting": IconReportMoney,
  "healthcare": IconStethoscope,
  "expenses": IconCash,
  "income": IconCurrencyDollar,
  "liabilities": IconReportMoney,
  "stock": IconChartBar,
  "setting": IconSettings,
  "setting-gear": IconSettings,
  "tool": IconTools,
//   "quality": IconCircleCheck,
//   "quality-3": IconCircleCheck,
  "quantity-1": IconCircle,

  // misc / fallbacks
  "folder": IconFolder,
};
